<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Handling</title>
</head>
<body>
<script>
    class MathUtil{
        static sum(...numbers){
            if (numbers.length === 0){
                // const eror = new Error("Total Pamater harus lebih dari 0")
                throw new Error("Total Pamater harus lebih dari 0");
            }

            let total = 0;
            for (const number of numbers){
                total+=number;
            }
            return total;
        }
    }


    try {
        // const result = MathUtil.sum();

        const result = MathUtil.sum(...[1,2,3,4,5]);
        console.log(result);
    } catch (error) {
        console.log("Ekooo");
        console.error(`Terjadi Eror ${error.message}`);
    } finally{
        console.log("Akan selalu di eksekusi terlepas dari eror");
    }

    console.info("Tetep lanjut kalo pake try catch")

    class Counter{
        #counter = 0;

        next(){
            try {
                return this.#counter;
                
            } finally {
                
                this.#counter++;
            }

        }
    }

    const counter = new Counter();
    console.log(counter.next())
    console.log(counter.next())
    console.log(counter.next())
    console.log(counter.next())
    console.log(counter.next())

</script>
</body>
</html>